### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by ConnorSkees**
Fixed some small errors I found while reading the documentation :)

### CODE REVIEW

**Comment by HeroicKatora** [comment]
@ConnorSkees The automatic links derived from symbol names only work on `nightly` rust but do not yet work on `stable`. So unfortunately the links need to point to the exact docs directly. But the first link is on the same page and can utililize the standard url anchor syntax of `#method.finish` which resolves to the html id `method.finish` that is generated for the inherent `fn finish(&self)` method .

**Comment by ConnorSkees** [comment]
It should be valid to write links in [this way](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md#additions-to-the-documentation-syntax). They both work correctly when testing just now (the former points to `.../image-png/target/doc/png/struct.StreamWriter.html#method.finish` and flush now goes to https://doc.rust-lang.org/nightly/std/io/trait.Write.html#tymethod.flush)

**Comment by HeroicKatora** [comment]
The tracking issue for intra doc links is: https://github.com/rust-lang/rust/issues/43466

**Comment by HeroicKatora** [comment]
Thanks for noticing @ConnorSkees and thank you for the review @kaj

**Pull request merged**
