### PR TITLE
implement deinterlacing for sub-8 bit pixels

### LINKED ISSUE #140: Index out of bounds error when decoding 1-bit image with IDENTITY
Ran into this when working on an example for #139 (using current API instead of the replacement):

```rust
    use std::fs::File;
    use png::{Decoder, HasParameters, Transformations};

    // transformations omitting EXPAND will produce indexed bytes for paletted images
    let transformations = Transformations::IDENTITY;

    // any image in pngsuite ending with "3pXX" is a paletted image
    let mut decoder = Decoder::new(File::open("tests/pngsuite/basi3p01.png").unwrap());
    decoder.set(transformations);

    let (_, mut reader) = decoder.read_info().unwrap();
    let mut buf = vec![0u8; reader.output_buffer_size()];
    reader.next_frame(&mut buf).unwrap();

    let palette = reader.info().palette.as_ref().unwrap();

    // these asserts are not reached
    assert_eq!(palette[buf[0] as usize], 238);
    assert_eq!(palette[buf[1] as usize], 0);
```

This panics with the following message and backtrace:

```
thread 'non_expanded_paletted' panicked at 'index out of bounds: the len is 128 but the index is 256', src/utils.rs:162:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   9: png::utils::expand_pass
             at src/utils.rs:176
  10: png::decoder::Reader<R>::next_frame
             at ./src/decoder/mod.rs:267
  11: non_expanded_paletted::non_expanded_paletted
             at tests/non_expanded_paletted.rs:15
  12: non_expanded_paletted::non_expanded_paletted::{{closure}}
             at tests/non_expanded_paletted.rs:2
  13: core::ops::function::FnOnce::call_once
             at /rustc/d35181ad8785fa958e43580a29a982afe02c728f/src/libcore/ops/function.rs:231
  14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d35181ad8785fa958e43580a29a982afe02c728f/src/liballoc/boxed.rs:704
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  16: test::run_test::run_test_inner::{{closure}}
             at /rustc/d35181ad8785fa958e43580a29a982afe02c728f/src/libstd/panicking.rs:272
             at /rustc/d35181ad8785fa958e43580a29a982afe02c728f/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468
```

I'd investigate this myself but I have work stuff to do so I may not be able to get to this for a while.

### PR DESCRIPTION
**Pull request by abonander**
closes #140

### CODE REVIEW

**Comment by abonander** [comment]
I don't think the implementation is correct yet, I have to keep working on this still.

**Comment by abonander** [comment]
I've been testing using this image: https://github.com/image-rs/image-png/blob/master/tests/pngsuite/basn3p01.png

This image has Adam7 interlacing; so I'm expecting these scanlines to start:

* Pass 1: 4 lines of `[0x0]` (4 bits of 0) for the first `n * 8` pixels
* Pass 2: 4 lines of `[0x0F]` (4 bits of 1) for the first `4 + n * 8` pixels

However, for the scanlines of pass 2 I'm getting `[0xF0]` instead which is really strange; are the bits supposed to be reversed, or is this due to the decoder not shifting the bits all the way down because it only received 4 for the scanline?

@HeroicKatora @martinlindhe @Shnatsel

**Comment by HeroicKatora** [comment]
The default `Transformation` options for `Decoder` will expand the pixels into full `u8` values by scaling them with a factor, here: https://github.com/image-rs/image-png/blob/2955393dbac799586ecc852b35f63a1ba26a0a4f/src/decoder/mod.rs#L309-L311

I suppose that would explain additional trailing zeroes?

**Comment by abonander** [comment]
@HeroicKatora I'm testing with just `IDENTITY`: https://github.com/image-rs/image-png/pull/142/files#diff-0bb1608151f4a8d1d056c46f21407090R7

**Comment by HeroicKatora** [comment]
@abonander I see, this is ' 1 bit (2 color) paletted ' image ([according to the png suite](http://www.schaik.com/pngsuite/pngsuite_int_gif.html)) so RGB is irrelevant anyways. It wasn't clear to me what the expected result is. With that additional information the behaviour seems less weird. 

1. According to [the specification](https://www.w3.org/TR/PNG/#7Scanline) the sample values (1-bit) are packed into the high-order bits in every scanline.
2. Scanlines that are not aligned to byte boundaries are padded.
3. The *scanlines* of the second pass consist of 4 pixels with the same palette index `1`. It follows that the 4 pixels of every scanline in the second pass are in the 4 high order bits of a single byte where the low order bits are zero padding.

**Comment by abonander** [comment]
@HeroicKatora I was looking at mainly the Wikipedia article which doesn't go into detail on scanline layout. I expected samples to start in the low-order bits which is why I was confused.

**Comment by abonander** [comment]
I see my change has now broken deinterlacing for bit depths > 8, I'll work on that tonight.

**Comment by abonander** [comment]
I'm close to a working implementation; I missed the bit in the spec how each scanline should start on a byte boundary so I will fix that tomorrow.

**Comment by abonander** [comment]
@HeroicKatora build is passing now, the failure is an ICE on nightly.

**Comment by HeroicKatora** [comment]
@abonander What's the status on this? There seem to be conflicts in `utils.rs` from the removal of `num-iter` but the changes in this PR seem like pure formatting.

**Comment by abonander** [comment]
@HeroicKatora most of the changes *are* in `utils.rs`; the formatting differences are due to changes which I need to rebase onto.

This was failing on nightly due to an ICE which didn't seem related to the change so I was waiting for the build to be rerun when nightly updated.

**Comment by HeroicKatora** [comment]
Ehm, I meant the changes with conflicts, sorry. We've remove the failing nightly build (only the one depending on `-Z minimal-versions` was failing, the normal nightly did not. so it really wasn't critical for merging and is now alled-failure) so might retest now.

**Comment by HeroicKatora** [comment]
Oh. Of course Travis relies on a possible merge to check a PR.

**Comment by HeroicKatora** [comment]
@abonander Since I didn't realize the conflict of removing `num-iter` and the pending changes here (and this one should have had priority), can I be of assistance for the rebase?

**Comment by HeroicKatora** [comment]
@abonander I had the time to rebase onto master. You can have a look [in this branch](https://github.com/HeroicKatora/image-png/tree/interlace). Sorry again for missing the coordination between the PRs here.

**Comment by abonander** [comment]
The rebase wasn't difficult but thanks anyway.

**Comment by HeroicKatora** [comment]
You missed an instance of `use num-iter::` that should be replaced with `(start..step).step_by(bits_pp * samp_mul)`.

**Comment by abonander** [comment]
Ah no, I just forgot that that got removed, sorry.

**Comment by HeroicKatora** [comment]
@abonander Also, congratulations, you are already one of the top contributors of the crate with this :smile:

**Pull request merged**
