### PR TITLE
Zlib Ng support

### PR DESCRIPTION
**Pull request by reinismu**
I have done my testing and `zlib-ng` is a big improvement for me.

With fast compression in around the same time I get 10x lower size.
At default settings it is around 70% faster

I did my examples using gstreamer plugin

before
```
gst-launch-1.0 videotestsrc is-live=false num-buffers=1000 ! videoconvert ! video/x-raw, format=RGBA, width=1920, height=1080 ! rspngenc compression-level=1 ! filesink location=test.mp4
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 0:00:07.891137892
Setting pipeline to NULL ...
Freeing pipeline ...


3,3G jūl 26 11:00 test.mp4

gst-launch-1.0 videotestsrc is-live=false num-buffers=1000 ! videoconvert ! video/x-raw, format=RGBA, width=1920, height=1080 ! rspngenc compression-level=0 ! filesink location=test1.mp4
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 0:00:17.072891381
Setting pipeline to NULL ...
Freeing pipeline ...

238M jūl 26 11:01 test1.mp4
```

after
```
gst-launch-1.0 videotestsrc is-live=false num-buffers=1000 ! videoconvert ! video/x-raw, format=RGBA, width=1920, height=1080 ! rspngenc compression-level=1 ! filesink location=test3.mp4
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 0:00:04.044782989
Setting pipeline to NULL ...
Freeing pipeline ...

422M jūl 26 11:29 test3.mp4

gst-launch-1.0 videotestsrc is-live=false num-buffers=1000 ! videoconvert ! video/x-raw, format=RGBA, width=1920, height=1080 ! rspngenc compression-level=0 ! filesink location=test3.mp4
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 0:00:10.079236244
Setting pipeline to NULL ...
Freeing pipeline ...

258M jūl 26 11:30 test3.mp4
```

Note: I was running on x64_86 linux

### CODE REVIEW

**Comment by reinismu** [comment]
Noticed that not Fast compression uses another library. Why not move it to new compression option?

**Comment by fintelia** [comment]
This can already be enabled by downstream users. No need to include here

**Comment by Shnatsel** [comment]
We might want to expose zlib-rs as an option for faster encoding/decoding at the cost of some `unsafe` code. `flate2` now exposes a feature to enable it. You get the performance of zlib-ng without any of the horrors of compiling C code, and it is marginally safer too.

**Comment by fintelia** [comment]
If you add `flate2 = { version = "1.0.33", features = "zlib-rs"}` to your Cargo.toml, this crate will use `zlib-rs` for encoding (if you pick Default or Best as the compression level). Same for `zlib-ng`.

The Fast compression level and all decoding uses fdeflate.

**Comment by Shnatsel** [comment]
That's true, I was just considering whether it could be exposed in a more user-friendly way and/or better documented.

A common concern with this method is that the `flate2` crate version may get out of sync between the `png` crate and the user's crate, but with `flate2` staying at 1.0 for so long it's probably not a big issue in practice, at least for now.

**Pull request closed without merging**
