### PR TITLE
Release v0.17.15

### PR DESCRIPTION
**Pull request by Shnatsel**
To go with https://github.com/image-rs/fdeflate/pull/42

### CODE REVIEW

**Comment by fintelia** [comment]
We should make sure to fix #537 before releasing

**Comment by Shnatsel** [comment]
Should I just run a mass search-and-replace and open a PR, or is there more to it than that?

**Comment by Shnatsel** [comment]
I opened #543 to rename the chunks.

**Review by fintelia — APPROVED** [review]

**Comment by Shnatsel** [comment]
I went ahead and merged the PR. I already ran a large-scale regression test on my corpora, so I'd appreciate if someone could run `cargo publish`.

**Comment by fintelia** [comment]
Published!

**Pull request merged**
