### PR TITLE
Yet another PR like #122

### PR DESCRIPTION
**Pull request by 3442853561**
Yet another PR like https://github.com/image-rs/image-png/pull/122
Add set_dpi

### CODE REVIEW

**Comment by HeroicKatora** [comment]
You don't need to open a new PR by the way, `git` allows you to force push the branch and Github then updates the PR automatically. Not sure if this is possible through the web-interface.

**Comment by fintelia** [comment]
Yeah, the commands would be something like:

```
$ git add foo.rs bar.rs
$ git commit --amend
$ git push --force-with-lease
```

**Comment by HeroicKatora** [comment]
Unfortunately, the unchecked cast from `f64` to `u32` in `from_dpi` [may not be as safe as one would like](https://doc.rust-lang.org/reference/expressions/operator-expr.html#semantics). Even if, as currently expected, it were to adopt saturating semantics the value could be unexpectedly lower than intended. It's also slightly confusing to have `set_dpi` but no `PixelDimensions::from_dpi` to parallel it.

The PR is already good without `set_dpi` as it is pure utility. Can we address and design that in separate issue?

**Comment by HeroicKatora** [comment]
The conversion from inch to meter also follows from the *definition* of an inch as `25.4mm`. Hence, the more precise number to use is `(1000.0/25.4)` but that shouldn't matter for most calculations.

**Comment by fintelia** [comment]
Superseded by #403

**Pull request closed without merging**
