### PR TITLE
add possiblity to encode pixel dimensions

### PR DESCRIPTION
**Pull request by Fight-For-Food**

### CODE REVIEW

**Comment by jonmmease** [comment]
Hi, I maintain a crate that depends on image-png and would be interested in this functionality as well. Is there anything I can do to help?

I tested against this branch and everything works as expected for my application ([VlConvert](https://github.com/vega/vl-convert)).

**Comment by fintelia** [comment]
Thanks for testing, that sort of check is super helpful!

@Fight-For-Food could you run `cargo fmt` to resolve the couple issues detected by CI? Other than that, this looks ready to merge

**Comment by Fight-For-Food** [comment]
Sorry for delay about fixing this PR. I am new with open source development.
I tried to use `cargo fmt`, but my personal settings are different with format of this project, and `cargo fmt` affect every source file. So I fix this CI check by my hands.
@fintelia  Maybe there is a good idea to add some _.rustfmt.toml_ to this repository?

**Comment by jonmmease** [comment]
Thanks @Fight-For-Food and @fintelia!

No rush, but do you have an estimate of when this functionality will be released to crates.io?

**Comment by jonmmease** [comment]
Perfect, thank you!

**Comment by jonmmease** [comment]
friendly ping regarding a release

**Pull request merged**
