### PR TITLE
Nicer ignore of parse errors in sBIT

### PR DESCRIPTION
**Pull request by kornelski**

### CODE REVIEW

**Comment by fintelia** [comment]
It would be nice to align the style with `parse_cicp`, `parse_mdcv`, and `parse_clli`. And ideally the rest of the optional metadata chunks as well.

**Comment by kornelski** [comment]
Oh, that would be even bigger churn. I'd rather not.

If I were going to touch them, I'd change them all to the style of `sBIT`, because having parsing code that can't use `Result` is too cumbersome, and having extra inner helper function is unnecessary if the failure can be ignored in `parse_chunk`.

**Comment by kornelski** [comment]
I've considered changing error handling for all ancillary chunks, but if we haven't had reports of unnecessary failures caused by them, then maybe they're not too broken in the wild, and it's okay to keep stricter checks.

**Comment by fintelia** [comment]
Switching the other ancillary chunks is tracked in #525.

We don't have to switch everything in one PR. But I would like to decide on _one_ approach to ignore errors from chunks and then make sure all changes move us towards that

**Pull request closed without merging**
