### PR TITLE
Add support for palette in fuzz roundtrip

### PR DESCRIPTION
**Pull request by ogarokpeter**
Add dummy palette generation in roundtrip fuzzing.

### CODE REVIEW

**Comment by fintelia** [comment]
I think it would be better to have the fuzzing target take in the whole palette as a `Vec<u8>` rather than generating based on a provided length.

**Comment by fintelia** [comment]
Much of the benefit of fuzzing comes from passing all sorts of weird and malformed inputs to the program to make sure they're all handled sensibly. The more we handcraft logic to assemble valid inputs, the less likely we'll find cases that we forget to address

**Comment by ogarokpeter** [comment]
Ok, agree with your point.

I've implemented fuzzing for palette.

**Comment by ogarokpeter** [comment]
Hello again!

Is there anything else to be done or is it good to go?

**Comment by fintelia** [comment]
Looks good to me

**Pull request merged**
